#!/system/xbin/bash
### FeraDroid Engine v15 | By FeraVolt. 2012

chmod 777 /sys/class/leds/lv5219lg:sled/brightness
echo 0 > /sys/class/leds/lv5219lg:sled/brightness
chown root.root /sys/class/leds/lv5219lg:sled/brightness
chmod 444 /sys/class/leds/lv5219lg:sled/brightness
chown root.root /sys/class/leds/lv5219lg:sled/brightness

