#!/bin/sh

usage() {
	echo "Usage: $0 [srctree]" >&2
	exit 1
}

cd "${1:-.}" || usage

if head=`git rev-parse --verify --short HEAD 2>/dev/null`; then
	if git name-rev --tags HEAD | grep -E '^HEAD[[:space:]]+(.*~[0-9]*|undefined)$' > /dev/null; then
		if tag=`git describe 2>/dev/null`; then
			echo $tag | awk -F- '{printf("-%05d-%s", $(NF-1),$(NF))}'
		else
			printf '%s%s' -g $head
		fi
	fi
	if git config --get svn-remote.svn.url >/dev/null; then
	        printf -- '-svn%s' "`git-svn find-rev $head`"
	fi
	git update-index --refresh --unmerged > /dev/null
	if git diff-index --name-only HEAD | grep -v "^scripts/package" \
	    | read dummy; then
		printf '%s' -dirty
	fi
	exit
fi

if hgid=`hg id 2>/dev/null`; then
	tag=`printf '%s' "$hgid" | cut -d' ' -f2`
	if [ -z "$tag" -o "$tag" = tip ]; then
		id=`printf '%s' "$hgid" | sed 's/[+ ].*//'`
		printf '%s%s' -hg "$id"
	fi
	case "$hgid" in
		*+|*+\ *) printf '%s' -dirty ;;
	esac
	exit
fi

if rev=`svn info 2>/dev/null | grep '^Last Changed Rev'`; then
	rev=`echo $rev | awk '{print $NF}'`
	printf -- '-svn%s' "$rev"
	exit
fi

