#!/bin/bash
DIR=$(cd $(dirname "$0"); pwd)
cd $DIR
rm -f -r ramdisk
if [ ! $1 ]
then
if [ -d ../input/ramdisk ]
	then 
		cp -f -r ../input/ramdisk ./ramdisk
	fi
else
	cp -f -r $1 ./ramdisk
fi

if [ -d ramdisk ]
then
	rm -f ramdisk.cpio.gz
	cd ramdisk
	find . | cpio -o -H newc | gzip > ../ramdisk.cpio.gz
	cd ..
	mv ramdisk.cpio.gz ../input
	rm -f -r ramdisk
	echo "Ramdisk created."
else
	echo "Ramdisk Folder not found!"
	exit
fi

