#!/system/xbin/sh
### FeraDroid Engine v18.1 | By FeraVolt. 2015 ###

mount -t ext3 -o rw /dev/block/vold/179:2 /mnt/sd-ext
mount -t ext3 -o rw /dev/block/mmcblk0p2 /mnt/sd-ext
sleep 1
mount -t ext4 -o rw /dev/block/vold/179:2 /mnt/sd-ext
mount -t ext4 -o rw /dev/block/mmcblk0p2 /mnt/sd-ext
sleep 1

