#!/system/xbin/sh
### FeraDroid Engine v18 | By FeraVolt. 2014 ###

for i in \
`find /data -iname "*.db"`; 
do \
	sqlite3 $i 'VACUUM;'; 
done;

for i in \
`find /data -iname "*.db"`; 
do \
	sqlite3 $i 'REINDEX;'; 
done;

sync;
