#!/system/xbin/sh
### FeraDroid Engine v18 | By FeraVolt. 2014 ###

if [ ! -e /data/local/animset ]
then
	if [ -e /data/data/com.android.providers.settings/databases/settings.db ]
	then
		echo "REPLACE INTO \"system\" VALUES(26,'window_animation_scale','0.25');REPLACE INTO \"system\" VALUES(27,'transition_animation_scale','0.25');" | sqlite3 /data/data/com.android.providers.settings/databases/settings.db
		kill `pidof system_server`
		echo "yes" > /data/local/animset
	fi
fi

