#!/system/xbin/sh
### FeraDroid Engine v18 | By FeraVolt. 2014 ###

echo '245760 925' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '384000 925' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '576000 975' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '768000 1075' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '998400 1275' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1113600 1300' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1190400 1325' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1228800 1350' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels


