#!/system/xbin/sh
### FeraDroid Engine v18 | By FeraVolt. 2015

echo 0 > /proc/sys/vm/swappiness
busybox swapoff /dev/block/ramzswap0
rzscontrol /dev/block/ramzswap0 --reset
busybox swapoff /dev/block/ramzswap0

