#!/sbin/sh
### FeraDroid Engine v14 | By FeraVolt. 2013

get_mtd() {
    local DEV="$(grep "\"$1\"" /proc/mtd | awk -F: '{print $1}')"
    local PATH=/dev/mtdblock
    DEV="${DEV##mtd}"
    echo "${DEV:+$PATH$DEV}"
}

mtd_system="$(get_mtd system)"
mount -o ro,remount -t yaffs2 $mtd_system /system;
mount -o ro,remount -t yaffs2 /dev/block/mtdblock2 /system
