#!/sbin/sh
### FeraLab ###

echo 998400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
setprop service.adb.root 1

/sbin/bootrec-device

if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
  rm /cache/recovery/boot
  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /cache
  umount -l /mnt/sdcard
  rm -r /sdcard
  rm -r /not/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  cp /recovery.fstab /etc/recovery.fstab
  mount /dev/block/mmcblk0p1 /sdcard
  setprop sys.usb.config mass_storage,adb
  setprop persist.service.adb.enable 1
  /sbin/recovery&
  /sbin/adbd recovery
else
  echo 998400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
fi

random_seed=/var/run/random-seed
if [ -f $random_seed ]; then
	cat $random_seed >/dev/urandom
else
 	touch $random_seed
fi

chmod 644 $random_seed
chmod 0666 /dev/frandom
chmod 0666 /dev/erandom
mv /dev/random /dev/random1
mv /dev/urandom /dev/urandom1
ln -s /dev/frandom /dev/random
ln -s /dev/erandom /dev/urandom
modprobe frandom
modprobe erandom
dd if=/dev/urandom of=$random_seed count=1 bs=256

/system/bin/chargemon

