#!/sbin/sh
### FeraLab ###

echo 998400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
setprop service.adb.root 1

/sbin/keycheck

if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
  rm /cache/recovery/boot
  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /cache
  umount -l /mnt/sdcard
  rm -r /sdcard
  rm -r /not/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  cp /recovery.fstab /etc/recovery.fstab
  mount /dev/block/mmcblk0p1 /sdcard
  setprop sys.usb.config mass_storage,adb
  setprop persist.service.adb.enable 1
  /sbin/recovery&
  /sbin/adbd recovery
fi

if [ -e /system/bin/charger ]
  echo "LB Kernel!"
else
  /system/bin/chargemon
fi

